apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-staging
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: hello:staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: apps/hello
    helm:
      parameters:
        - name: host
          value: hello-staging.cereal.box
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-staging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
