apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/akuity/kargo-charts
    chart: kargo
    targetRevision: 1.9.4
    helm:
      values: |
        api:
          adminAccount:
            enabled: true
          secret:
            name: kargo-admin
          host: kargo.cereal.box
          ingress:
            enabled: true
            ingressClassName: traefik
            tls:
              enabled: true
          tls:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
