apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jared-paul/homelab.git
    targetRevision: main
    path: home/kargo
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
