apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-custom-dns
  namespace: pihole
data:
  custom.list: |
    192.168.0.19 argocd.cereal.box
    192.168.0.19 pihole.cereal.box
    192.168.0.19 kargo.cereal.box
