apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-custom-dns
  namespace: pihole
data:
  02-custom-dns.conf: |
    address=/argocd.cereal.box/192.168.0.19
    address=/pihole.cereal.box/192.168.0.19
    address=/kargo.cereal.box/192.168.0.19
