apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: production
  namespace: hello
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: hello
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: hello-promote
          as: promo
