apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: hello-promote
  namespace: hello
spec:
  vars:
    - name: gitopsRepo
      value: https://github.com/jared-paul/homelab.git
    - name: imageRepo
      value: ghcr.io/jared-paul/hello
  steps:
    - uses: git-clone
      config:
        repoURL: ${{ vars.gitopsRepo }}
        checkout:
          - branch: main
            path: ./repo
    - uses: yaml-update
      as: update
      config:
        path: ./repo/apps/hello/values-${{ ctx.stage }}.yaml
        updates:
          - key: image.tag
            value: ${{ imageFrom(vars.imageRepo).Tag }}
    - uses: git-commit
      as: commit
      config:
        path: ./repo
        messageFromSteps:
          - update
    - uses: git-push
      config:
        path: ./repo
    - uses: argocd-update
      config:
        apps:
          - name: hello-${{ ctx.stage }}
            sources:
              - repoURL: ${{ vars.gitopsRepo }}
                desiredRevision: ${{ outputs.commit.commit }}
