apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: hello
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: hello
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - uses: argocd-update
          config:
            apps:
              - name: hello-staging
                namespace: argocd
